main: me.sirfaizdat.sfcore.SFCore
name: ${project.name}
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: SirFaizdat
commands:
  sfcore:
    description: Commands to manage SFCore.